/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.Ficha;
import datos.Jugador;
import datos.Tipo;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import negocios.Juego;
import static negocios.Juego.crearFantasma;

/**
 *
 * @author braya
 */
public class MenuJugadores extends javax.swing.JFrame {

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int tamañoVentana = screenSize.height - 100;
    int tamañoImagenes = screenSize.height - 150;
    Tipo tipo;

    /**
     * Creates new form MenuNuevoJuevo
     */
    public MenuJugadores() {
        initComponents();

        this.setSize(new Dimension(tamañoVentana, tamañoVentana));
        this.setMinimumSize(new Dimension(tamañoVentana, tamañoVentana));
        this.setMaximumSize(new Dimension(tamañoVentana, tamañoVentana));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public Tipo elegirTipo() {
        tipo = Juego.crearTipo2();
        if (seleccionTablero8x8.isSelected()) {
            tipo = Juego.crearTipo1();
            return tipo;
        }
        if (seleccionTablero10x10.isSelected()) {
            tipo = Juego.crearTipo2();
            return tipo;
        }
        if (seleccionTablero12x12.isSelected()) {
            tipo = Juego.crearTipo3();
            return tipo;
        }
        JOptionPane.showMessageDialog(null, "Por defecto se seleccionara tablero 10x10"); //posiblemente nunca pase porque debe seleccionarse alguno para poder llamar este metodo
        return tipo;
    }

    public ArrayList<Jugador> elegirJugadores() {
        int posicionJugador[] = {0, 0};
        ArrayList<Jugador> jugadores = new ArrayList<Jugador>();
        Jugador jugador1 = new Jugador(1, nombreJug1.getText(), new Ficha(colorJug1.getSelectedItem().toString()));
        Jugador jugador2 = new Jugador(2, nombreJug2.getText(), new Ficha(colorJug2.getSelectedItem().toString()));
        Jugador jugador3 = new Jugador(3, nombreJug3.getText(), new Ficha(colorJug3.getSelectedItem().toString()));
        Jugador jugador4 = new Jugador(4, nombreJug4.getText(), new Ficha(colorJug4.getSelectedItem().toString()));

        switch (tipo.getTamanoTablero()) {
            case 64:
                posicionJugador[0] = 7;
                break;
            case 100:
                posicionJugador[0] = 9;
                break;
            case 144:
                posicionJugador[0] = 11;
                break;
        }
        posicionJugador[1] = -1;

        if (seleccion1Jugador.isSelected()) {
            jugadores.add(0, jugador1);
            Jugador Fantasma1 = crearFantasma(2, tipo.getTamanoTablero());
            Jugador Fantasma2 = crearFantasma(3, tipo.getTamanoTablero());
            Jugador Fantasma3 = crearFantasma(4, tipo.getTamanoTablero());
            jugadores.add(1, Fantasma1);
            jugadores.add(2, Fantasma2);
            jugadores.add(3, Fantasma3);

            jugadores.get(0).setPosicion(posicionJugador);
        }
        if (seleccion2Jugadores.isSelected()) {
            jugadores.add(0, jugador1);
            jugadores.add(1, jugador2);
            for (int i = 0; i < jugadores.size(); i++) {
                jugadores.get(i).setPosicion(posicionJugador);
            }
        }
        if (seleccion3Jugadores.isSelected()) {
            jugadores.add(0, jugador1);
            jugadores.add(1, jugador2);
            jugadores.add(2, jugador3);
            for (int i = 0; i < jugadores.size(); i++) {
                jugadores.get(i).setPosicion(posicionJugador);
            }
        }
        if (seleccion4Jugadores.isSelected()) {
            jugadores.add(0, jugador1);
            jugadores.add(1, jugador2);
            jugadores.add(2, jugador3);
            jugadores.add(3, jugador4);
            for (int i = 0; i < jugadores.size(); i++) {
                jugadores.get(i).setPosicion(posicionJugador);
            }
        }
        return jugadores;//posiblemente nunca pase porque debe seleccionarse alguno para poder llamar este metodo
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        seleccion2Jugadores = new javax.swing.JRadioButton();
        seleccion3Jugadores = new javax.swing.JRadioButton();
        seleccion4Jugadores = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        seleccion1Jugador = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        seleccionTablero8x8 = new javax.swing.JRadioButton();
        seleccionTablero10x10 = new javax.swing.JRadioButton();
        seleccionTablero12x12 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nombreJug1 = new javax.swing.JTextField();
        colorJug1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombreJug2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        colorJug2 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nombreJug4 = new javax.swing.JTextField();
        colorJug4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        nombreJug3 = new javax.swing.JTextField();
        colorJug3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        botonIniciar = new javax.swing.JButton();
        botonMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de Jugadores"));

        buttonGroup1.add(seleccion2Jugadores);
        seleccion2Jugadores.setText("2 jugadores");
        seleccion2Jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion2JugadoresActionPerformed(evt);
            }
        });

        buttonGroup1.add(seleccion3Jugadores);
        seleccion3Jugadores.setText("3 jugadores");
        seleccion3Jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion3JugadoresActionPerformed(evt);
            }
        });

        buttonGroup1.add(seleccion4Jugadores);
        seleccion4Jugadores.setText("4 jugadores");
        seleccion4Jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion4JugadoresActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el numero de jugadores");

        buttonGroup1.add(seleccion1Jugador);
        seleccion1Jugador.setText("1 jugador (Modo Supervivencia)");
        seleccion1Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion1JugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccion1Jugador)
                    .addComponent(jLabel1)
                    .addComponent(seleccion2Jugadores)
                    .addComponent(seleccion3Jugadores)
                    .addComponent(seleccion4Jugadores))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(seleccion1Jugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccion2Jugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccion3Jugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccion4Jugadores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño del  tablero"));

        jLabel2.setText("Seleccione el tamaño del tablero");

        buttonGroup2.add(seleccionTablero8x8);
        seleccionTablero8x8.setText("Tablero 8x8");

        buttonGroup2.add(seleccionTablero10x10);
        seleccionTablero10x10.setText("Tablero 10x10");

        buttonGroup2.add(seleccionTablero12x12);
        seleccionTablero12x12.setText("Tablero 12x12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(seleccionTablero12x12)
                    .addComponent(seleccionTablero10x10)
                    .addComponent(seleccionTablero8x8))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(seleccionTablero8x8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionTablero10x10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionTablero12x12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugadores"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 1")));

        jLabel3.setText("Nombre");

        nombreJug1.setEditable(false);
        nombreJug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJug1ActionPerformed(evt);
            }
        });

        colorJug1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione un color 1", "rojo", "verde", "azul", "amarillo" }));
        colorJug1.setEnabled(false);
        colorJug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJug1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Color Ficha");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(colorJug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nombreJug1))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorJug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 2"));

        jLabel5.setText("Nombre");

        nombreJug2.setEditable(false);
        nombreJug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJug2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Color Ficha");

        colorJug2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione un color 2", "rojo", "verde", "azul", "amarillo" }));
        colorJug2.setEnabled(false);
        colorJug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJug2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(colorJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(nombreJug2))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombreJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 4"));

        jLabel7.setText("Nombre");

        nombreJug4.setEditable(false);

        colorJug4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione un color 4", "rojo", "verde", "azul", "amarillo" }));
        colorJug4.setEnabled(false);

        jLabel8.setText("Color Ficha");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(colorJug4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nombreJug4))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJug4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorJug4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 3"));

        jLabel9.setText("Nombre");

        nombreJug3.setEditable(false);

        colorJug3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione un color 3", "rojo", "verde", "azul", "amarillo" }));
        colorJug3.setEnabled(false);

        jLabel10.setText("Color Ficha");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(colorJug3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(nombreJug3))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJug3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorJug3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonIniciar.setText("Iniciar Juego");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        botonMenuPrincipal.setText("Menu Principal");
        botonMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonMenuPrincipal)
                        .addGap(131, 131, 131)
                        .addComponent(botonIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(botonIniciar)
                    .addComponent(botonMenuPrincipal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void nombreJug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJug2ActionPerformed
    }//GEN-LAST:event_nombreJug2ActionPerformed

    private void nombreJug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJug1ActionPerformed

    }//GEN-LAST:event_nombreJug1ActionPerformed

    private void seleccion1JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion1JugadorActionPerformed
        if (seleccion1Jugador.isSelected()) {
            nombreJug1.setEditable(true);
            colorJug1.setEnabled(true);
            nombreJug2.setEditable(false);
            nombreJug2.setText("");
            colorJug2.setEnabled(false);
            nombreJug3.setEditable(false);
            nombreJug3.setText("");
            colorJug3.setEnabled(false);
            nombreJug4.setEditable(false);
            nombreJug4.setText("");
            colorJug4.setEnabled(false);
            colorJug2.setSelectedItem("seleccione un color 2");
            colorJug3.setSelectedItem("seleccione un color 3");
            colorJug4.setSelectedItem("seleccione un color 4");
        }
    }//GEN-LAST:event_seleccion1JugadorActionPerformed

    private void seleccion2JugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion2JugadoresActionPerformed
        if (seleccion2Jugadores.isSelected()) {
            nombreJug1.setEditable(true);
            colorJug1.setEnabled(true);
            nombreJug2.setEditable(true);
            colorJug2.setEnabled(true);
            nombreJug3.setEditable(false);
            nombreJug3.setText("");
            colorJug3.setEnabled(false);
            nombreJug4.setEditable(false);
            nombreJug4.setText("");
            colorJug4.setEnabled(false);
            colorJug3.setSelectedItem("seleccione un color 3");
            colorJug4.setSelectedItem("seleccione un color 4");
        }
    }//GEN-LAST:event_seleccion2JugadoresActionPerformed

    private void seleccion3JugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion3JugadoresActionPerformed
        if (seleccion3Jugadores.isSelected()) {
            nombreJug1.setEditable(true);
            colorJug1.setEnabled(true);
            nombreJug2.setEditable(true);
            colorJug2.setEnabled(true);
            nombreJug3.setEditable(true);
            colorJug3.setEnabled(true);
            nombreJug4.setEditable(false);
            nombreJug4.setText("");
            colorJug4.setEnabled(false);
            colorJug4.setSelectedItem("seleccione un color 4");
        }
    }//GEN-LAST:event_seleccion3JugadoresActionPerformed

    private void seleccion4JugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion4JugadoresActionPerformed
        if (seleccion4Jugadores.isSelected()) {
            nombreJug1.setEditable(true);
            colorJug1.setEnabled(true);
            nombreJug2.setEditable(true);
            colorJug2.setEnabled(true);
            nombreJug3.setEditable(true);
            colorJug3.setEnabled(true);
            nombreJug4.setEditable(true);
            colorJug4.setEnabled(true);
        }
    }//GEN-LAST:event_seleccion4JugadoresActionPerformed

    private void colorJug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJug1ActionPerformed
    }//GEN-LAST:event_colorJug1ActionPerformed

    private void colorJug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJug2ActionPerformed
    }//GEN-LAST:event_colorJug2ActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed

        if ((seleccion1Jugador.isSelected() && (colorJug1.getSelectedItem() == "seleccione un color 1"))
                || (seleccion2Jugadores.isSelected() && (colorJug1.getSelectedItem() == "seleccione un color 1" || colorJug2.getSelectedItem() == "seleccione un color 2"))
                || (seleccion3Jugadores.isSelected() && (colorJug1.getSelectedItem() == "seleccione un color 1" || colorJug2.getSelectedItem() == "seleccione un color 2" || colorJug3.getSelectedItem() == "seleccione un color 3"))
                || (seleccion4Jugadores.isSelected() && (colorJug1.getSelectedItem() == "seleccione un color 1" || colorJug2.getSelectedItem() == "seleccione un color 2" || colorJug3.getSelectedItem() == "seleccione un color 3" || colorJug4.getSelectedItem() == "seleccione un color 4"))) {
            JOptionPane.showMessageDialog(null, "Hay jugadores que aun no seleccionan color");

        } else if (colorJug1.getSelectedItem() == colorJug2.getSelectedItem()
                || colorJug1.getSelectedItem() == colorJug3.getSelectedItem()
                || colorJug1.getSelectedItem() == colorJug4.getSelectedItem()
                || colorJug2.getSelectedItem() == colorJug3.getSelectedItem()
                || colorJug2.getSelectedItem() == colorJug3.getSelectedItem()
                || colorJug3.getSelectedItem() == colorJug4.getSelectedItem()) {

            JOptionPane.showMessageDialog(null, "Todos los Jugadores deben tener colores Distintos");

        } else if (!(seleccionTablero8x8.isSelected() || seleccionTablero10x10.isSelected() || seleccionTablero12x12.isSelected())) {
            JOptionPane.showMessageDialog(null, "Se debe elegir un tamaño para el tablero");
        } else if (!(seleccion1Jugador.isSelected() || seleccion2Jugadores.isSelected() || seleccion3Jugadores.isSelected() || seleccion4Jugadores.isSelected())) {
            JOptionPane.showMessageDialog(null, "Se debe elegir un numero de jugadores");
        } else {
            UIGrafica gui = new UIGrafica(this.elegirTipo(), this.elegirJugadores());
            gui.setVisible(true);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Turno del jugador 1: " + nombreJug1.getText());
        }

    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuPrincipalActionPerformed

        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonMenuPrincipal;
    private javax.swing.JButton botonSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> colorJug1;
    private javax.swing.JComboBox<String> colorJug2;
    private javax.swing.JComboBox<String> colorJug3;
    private javax.swing.JComboBox<String> colorJug4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField nombreJug1;
    private javax.swing.JTextField nombreJug2;
    private javax.swing.JTextField nombreJug3;
    private javax.swing.JTextField nombreJug4;
    private javax.swing.JRadioButton seleccion1Jugador;
    private javax.swing.JRadioButton seleccion2Jugadores;
    private javax.swing.JRadioButton seleccion3Jugadores;
    private javax.swing.JRadioButton seleccion4Jugadores;
    private javax.swing.JRadioButton seleccionTablero10x10;
    private javax.swing.JRadioButton seleccionTablero12x12;
    private javax.swing.JRadioButton seleccionTablero8x8;
    // End of variables declaration//GEN-END:variables
}
